config/routes.rb
Rails.application.routes.draw do
  
  resources :patients
  resources :appointments
  root 'home#index'
  
  get '/about' => 'home#about'
  

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  before_save :build_patient, :on => :create
  belongs_to :patient
  validates :date, :time, presence: true
  attr_accessor :patient_name
  scope :for_today, -> {where(date: Date.today)}

  after_initialize do |appointment|
      appointment.date = appointment.date || Date.today + 1
      appointment.time = appointment.time || Time.parse("13:30")
  end

  def patient_name
    @patient_name || (if patient.present? then patient.full_name end)
  end

  def build_patient
    if self.is_first
      puts "first time patient"
      puts self.patient_name
      self.patient_id = Patient.create({:first_name => @patient_name}).id;
    end
  end
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :appointments
  validates :first_name, presence: true
  def full_name
    [first_name,last_name].join(' ')
  end
  def address
    [street, city].join(', ')
  end
  
  def self.search(search)
    where("lower(first_name) LIKE ?", "%#{search.downcase}%")
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
    @appointment = Appointment.new
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to appointments_url, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:time, :referenceid, :date, :is_first, :patient_id, :patient_name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @appointment = Appointment.new
    appointments_for_today = Appointment.for_today
    
    @new_patients_for_today_count = 0;
    appointments_for_today.each do |app|
      if app.is_first then @new_patients_for_today_count += 1 end
    end
      
      @appointments_for_today_count = appointments_for_today.count
  end

  def about

  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
    if params[:search]
      @patients = Patient.search(params[:search]).order("created_at DESC")
    elsif params[:term]
       @patients = Patient.order(:first_name).where("first_name like ?", "%#{params[:term]}%")
       render json: get_patient_info(@patients)
    else
      @patients = Patient.all.order("created_at DESC")
    end
  end
  
  def get_patient_info(patients)
    patientinfo = Array.new
    for p in patients
      pat = PatientInfo.new
      pat.label(p.full_name)
      pat.value(p.id)
      patientinfo.append(pat)
    end
    patientinfo
  end
  
  class PatientInfo
    def label
      @label
    end
    def label(name)
      @label = name
    end
    def value
      @value
    end
    def value(id)
      @value = id
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :cell_phone, :alt_phone, :email, :street, :city, :state, :country, :dob, :registration_on, :reference_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    puts flash_type
    case flash_type
      when "notice"
        "success"
      else
        flash_type.to_s
    end
  end

end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
    <%= f.label :date %><br>
    <%= f.text_field :date, :class=>'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label :time %><br>
	<%if @appointment.time.present? %>
    <%= f.text_field :time, :value => @appointment.time.strftime("%I:%M %P"), :class=>'form-control'%>
	<%else%>
	<%= f.text_field :time, :class=>'form-control'%>
	<%end%>
  </div>
	
  <div class="form-group">
    <%= f.hidden_field :patient_id , :class=>'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :patient_name %><br>
    <%= f.text_field :patient_name , :class=>'form-control', data:{autocomplete_source:patients_path}%>
  </div>
  <div class="form-group">
    <%= f.label :is_first %><br>
    <%= f.check_box :is_first, :class=>'checkbox' %>
  </div>
  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>

app/views/appointments/_quick_create.html.erb
<%= form_for(appointment) do |f| %>
<div class="row">
  <div class="col-sm-6 col-md-4">
        <h3>New Patient</h3>
        <p>
				  <%= f.text_field :date, :class=>'form-control'%>
				</p>
        <p>
					<div class="row">
						<div class="col-sm-6 col-md-6">
							<%= f.submit "Quick Create", class: "btn btn-default"%>
						</div>
						<div class="col-sm-6 col-md-6">
							<%= link_to 'New Appointment', new_appointment_path , class: "btn btn-default pull-right" %>
						</div>
					</div>
				</p>
      </div>
</div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<%= render 'shared/flash_messages' if !flash.empty? %>

<div class="panel panel-default">
	<!-- Default panel contents -->
	<div class="panel-heading">
		Listing Appointments
	</div>

	<table class="table table-condensed table-striped  table-hover table-bordered">
		<thead>
			<tr>
				<th>Date</th>
				<th>Time</th>
				<th>Patient</th>
				<th>First Appointment</th>
				<th colspan="5"></th>
			</tr>
		</thead>

		<tbody>
			<% @appointments.each do |appointment| %>
			<tr>
				<td><%= appointment.date %></td>
				<td><%= appointment.time.to_s(:time) %></td>
				<td><%= appointment.patient_name %></td>
				<td><%= appointment.is_first %></td>
				<td>
				<div class="btn-group">
					<%= link_to 'Show', appointment, class: "btn btn-xs" %>
					<%= link_to 'Edit', edit_appointment_path(appointment), class: "btn btn-xs"  %>
					<%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs" %>
				</div></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>
<br>
<%= render partial:"quick_create", locals:{appointment:@appointment} %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<div class="form-group">
  <label for="Date" class="col-sm-2 control-label">Date:</label>
  <%= @appointment.date %>
</div>

<div class="form-group">
  <label for="Time" class="col-sm-2 control-label">Time:</label>
  <%= @appointment.time.strftime('%I:%M %P') %>
</div>

<div class="form-group">
  <label for="Patient" class="col-sm-2 control-label">Patient:</label>
  <%= @appointment.patient_name %>
</div>

<div class="form-group">
  <label for="FirstAppointment" class="col-sm-2 control-label">First Appointment:</label>
  <%= @appointment.is_first %>
</div>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="panel panel-primary">
      <div class="panel-heading text-center">
        Today's appointments
        <h1><%= @appointments_for_today_count %></h1>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="panel panel-primary">
      <div class="panel-heading text-center">
        First time appointments
        <h1><%= @new_patients_for_today_count %></h1>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="panel panel-primary">
      <div class="panel-heading text-center">
        Today's appointments
        <h1 class="center">25</h1>
      </div>
    </div>
  </div>
</div>


<div class="row">
  <%= render partial:"appointments/quick_create", locals:{appointment:@appointment} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Med</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render 'shared/navigation' %>
	<div class="container">
		<%= yield %>

		<%= render 'shared/modal' %>

	</div>

</body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, :class=>'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, :class=>'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :cell_phone %><br>
    <%= f.text_field :cell_phone, :class=>'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :alt_phone %><br>
    <%= f.text_field :alt_phone, :class=>'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, :class=>'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :street %><br>
    <%= f.text_field :street, :class=>'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, :class=>'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :state %><br>
    <%= f.text_field :state, :class=>'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :country %><br>
    <%= f.text_field :country, :class=>'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :dob %><br>
    <%= f.date_select :dob, :class=>'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :registration_on %><br>
    <%= f.text_field :registration_on, :class=>'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :reference_id %><br>
    <%= f.text_field :reference_id, :class=>'form-control' %>
  </div>
	
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
	<%= form_tag(patients_path, :method => 'get', :id => 'search_form') do %>
		<%= text_field_tag :search, params[:search], placeholder: 'Search Patients' %>
		<%= submit_tag "Search", :name => nil %>
	<% end %>
</div>

<div class="panel panel-default">
	<!-- Default panel contents -->
	<div class="panel-heading">
		Listing Patients
	</div>

	<% if @patients.present? %>
	<table class="table table-condensed table-striped  table-hover table-bordered">
		<thead>
			<tr>
		        <th class="col-sm-2">Full name</th>
		        <th>Cell phone</th>
		        <th>Email</th>
		        <th>Address</th>
		        <th>Reference</th>
		        <th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
		    <% @patients.each do |patient| %>
		      <tr>
		        <td><%= patient.full_name %></td>
		        <td><%= patient.cell_phone %></td>
		        <td><%= patient.email %></td>
		        <td><%= patient.address %></td>
		        <td><%= patient.reference_id %></td>
				<td>
					<div class="btn-group">
				
		             	<%= link_to 'Show', patient, class: "btn btn-default"%> 
						<%= link_to 'Edit', edit_patient_path(patient), class: "btn btn-default"%> 
						<%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default"%>
		             
					</div>
				</td>
			 </tr>
			 <% end %>
		 </tbody>
	 </table>
	 
	 <% else %>
	   <p>There are no patients containing the first name <%= params[:search] %>.</p>
	 <% end %>
 </div>



<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<div>
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @patient.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @patient.last_name %>
</p>

<p>
  <strong>Cell phone:</strong>
  <%= @patient.cell_phone %>
</p>

<p>
  <strong>Alt phone:</strong>
  <%= @patient.alt_phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @patient.email %>
</p>

<p>
  <strong>Street:</strong>
  <%= @patient.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @patient.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @patient.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @patient.country %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @patient.dob %>
</p>

<p>
  <strong>Registration on:</strong>
  <%= @patient.registration_on %>
</p>

<p>
  <strong>Reference:</strong>
  <%= @patient.reference_id %>
</p>

<div class="panel panel-default">
	<!-- Default panel contents -->
	<div class="panel-heading">
		Listing Appointments
	</div>

	<table class="table table-condensed table-striped  table-hover table-bordered">
		<thead>
			<tr>
				<th>Date</th>
				<th>Time</th>
				<th>Patient</th>
				<th>First Appointment</th>
				<th colspan="5"></th>
			</tr>
		</thead>

		<tbody>
			<% @patient.appointments.each do |appointment| %>
			<tr>
				<td><%= appointment.date %></td>
				<td><%= appointment.time.to_s(:time) %></td>
				<td><%= appointment.patient.full_name %></td>
				<td><%= appointment.is_first %></td>
				<td>
				<div class="btn-group">
					<%= link_to 'Show', appointment, class: "btn btn-default" %>
					<%= link_to 'Edit', edit_appointment_path(appointment), class: "btn btn-default"  %>
					<%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
				</div></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

<%= link_to 'Edit', edit_patient_path(@patient) %> | <%= link_to 'Back', patients_path %> </div>

app/views/shared/_flash_messages.html.erb
<div id="flash_messages">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, :class => "alert alert-#{bootstrap_class_for(key)} fade in") %>
  <% end %>
</div>

app/views/shared/_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Modal title</h4>
			</div>
			<div class="modal-body">
				...
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<button type="button" class="btn btn-primary">Save changes</button>
			</div>
		</div>
	</div>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%=link_to 'Med', root_path, class:'navbar-brand'%>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="dropdown">
					<%= link_to patients_path, data:{toggle:"dropdown"}, role:"button",'aria-expanded':"false", 'aria-haspopup':"true", :class=>"dropdown-toggle", :id => 'patients_menu' do %>
					Patients <span class="caret"></span>
					<% end %>
					<ul class="dropdown-menu">
						<li>
							<%= link_to "Search", patients_path %>
						</li>
						<li>
							<%= link_to 'Add New', new_patient_path %>
						</li>
					</ul>
				</li>
				<li class="dropdown">
					<%= link_to appointments_path, data:{toggle:"dropdown"}, role:"button",'aria-expanded':"false", 'aria-haspopup':"true", :class=>"dropdown-toggle" , :id => 'appointments_menu' do %>
					Appointments <span class="caret"></span>
					<% end %>
					<ul class="dropdown-menu">
						<li>
							<%= link_to 'Search', appointments_path %>
						</li>
						<li>
							<%= link_to 'Add New', new_appointment_path %>
						</li>
					</ul>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li><button type=button class="btn btn-link" id="helpbutton">Help</li>
					<li>
						<%= form_tag(patients_path,:class=>'navbar-form navbar-left', :method => 'get', :id => 'search_form') do %>
							<%= text_field_tag :search, params[:search], placeholder: 'Search Patients', :class => 'form-control' %>
							<%= submit_tag "Search", :name => nil, :class => 'btn btn-primary btn-lg' %>
						<% end %>
					</li>

				<li><button type="button" class="btn" data-toggle="modal" data-target="#myModal">
					Launch demo modal
				</button></li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>